// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plankbahpovnmigfndqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYW5rYmFocG92bm1pZ2ZuZHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTE2NzUsImV4cCI6MjA3MzE2NzY3NX0.MCtV6So9yWtDifTwWf00p23V2LJ1aSF3aboTEKtjEh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});